#!/usr/bin/env bash
# Create RSA
# Define variables for key name, key length, and passphrase
key_name="school"
key_length=4096
passphrase="betty"

# Create the RSA key pair with the specified parameters
ssh-keygen -t rsa -b $key_length -f ~/.ssh/$key_name -q -N "$passphrase"

echo "RSA key pair created successfully with the following parameters:"
echo "Key name: $key_name"
echo "Key length: $key_length"
echo "Passphrase: $passphrase"
